controllers/gestion_plantillas.go
controllers/services.go
helpers/calculos.go
helpers/plantillas.go
helpers/utilidades.go

feat: calculos ruler

---

controllers/gestion_plantillas.go
controllers/gestion_resoluciones.go
helpers/resoluciones.go
helpers/utilidades.go
models/contenido_resolucion.go
models/resoluciones.go
routers/commentsRouter_controllers.go
routers/router.go
swagger/swagger.json

feat: Se desarrolla el controlador y las funcionalidades para el módulo de gestión de resoluciones. #10

feat: gestion resoluciones

---

tests/controllers/gestion_plantillas_test.go
tests/controllers/gestion_resoluciones_test.go
tests/controllers/services_test.go
tests/main_test.go

feat: Se generan pruebas unitarias de los controladores desarrollados hasta el momento #13

feat: Se generan pruebas

---

controllers/gestion_resoluciones.go
helpers/plantillas.go
helpers/resoluciones.go
helpers/utilidades.go

fix: Se corrigen funcionalidades de acuerdo a hallazgos en pruebas funcionales. #13

fix: Se corrigen funcionalidades

---

helpers/calculos.go

hotfix: se corrige carga de punto salarial independientemente de la vigencia

hotfix: punto salarial

---

controllers/expedir_resolucion.go
tests/controllers/expedir_resolucion_test.go
tests/controllers/gestion_resoluciones_test.go
tests/controllers/gestion_vinculaciones_test.go

test: Se realizan pruebas unitarias

test: Se realizan pruebas unitarias

---

helpers/calculos.go
helpers/docentes.go
helpers/documentos.go
helpers/expedir_resolucion.go
helpers/expedir_resoluciones.go
helpers/vinculaciones.go

hotfix: Se hacen correcciones menores.

hotfix: Se hacen correcciones menores.

---

helpers/calculos.go
helpers/documentos.go
helpers/vinculaciones.go
models/datos_vinculacion.go
models/desagregado_contrato.go

feat: Almacenamiento y consulta de reporte de desagregados en resolución pdf.

feat:  reporte de desagregados

---

helpers/calculos.go
helpers/documentos.go
helpers/vinculaciones.go
models/datos_vinculacion.go
models/desagregado_contrato.go

feat: reporte de rubros. udistrital/resoluciones_cliente_v2#19

feat: reporte de rubros

---

controllers/gestion_plantillas.go
controllers/gestion_resoluciones.go
controllers/gestion_vinculaciones.go
helpers/documentos.go
helpers/vinculaciones.go
main.go
swagger/swagger.json

feat: Se aplican correcciones segun observaciones en pruebas de carga y seguridad.

feat: Se aplican correcciones

---

conf/app.conf
helpers/docentes.go
helpers/documentos.go
helpers/expedir_resoluciones.go
helpers/plantillas.go
helpers/resoluciones.go
helpers/utilidades.go
helpers/vinculaciones.go

management: Correcciones menores.

management: Correcciones menores.

---

helpers/documentos.go

fix: Se corrige conversión de semanas a meses en pdf

fix: Se corrige conversión de semanas a meses en pdf

---

helpers/vinculaciones.go
models/disponibilidad_vinculacion.go

fix: Se agrega campo faltante

---

helpers/vinculaciones.go

fix: Se corrige campo de relación

fix: Se corrige campo de relación

---

helpers/vinculaciones.go

fix: Se agrega desactivación de vinculación modificada.

fix: Se agrega desactivación de vinculación modificada. 

---

helpers/calculos.go
helpers/documentos.go
helpers/expedir_resoluciones.go
helpers/utilidades.go
helpers/vinculaciones.go

feat: se desarrolla lógica de trazabilidad y se aplica en la generación del documento pdf

feat: se desarrolla lógica de trazabilidad

---

helpers/expedir_resoluciones.go

fix: Se corrige información faltante en reducción

fix: Se corrige información faltante en reducción

---

helpers/documentos.go
helpers/vinculaciones.go

fix: se ajusta trazabilidad en reducciones.

fix: se ajusta trazabilidad en reducciones

---

helpers/documentos.go
helpers/expedir_resoluciones.go
helpers/vinculaciones.go

fix: se ajusta trazabilidad en reducciones.

fix: se ajusta trazabilidad en reducciones.

---

conf/app.conf
helpers/calculos.go
helpers/docentes.go
helpers/documentos.go
helpers/expedir_resolucion.go
helpers/expedir_resoluciones.go
helpers/plantillas.go
helpers/resoluciones.go
helpers/utilidades.go
helpers/vinculaciones.go
models/disponibilidad_vinculacion.go

management: actualización prod MID. udistrital/resoluciones_cliente_v2#40

management: actualización prod MID

---

controllers/gestion_vinculaciones.go
helpers/documentos.go
helpers/expedir_resolucion.go
helpers/resoluciones.go
routers/commentsRouter_controllers.go
swagger/swagger.json

feat: revisión formato tablas y otras correcciones

feat: revisión formato tablas y otras correcciones

---

tests/controllers/gestion_resoluciones_test.go
tests/controllers/gestion_vinculaciones_test.go
tests/main_test.go

test: Se ajustan pruebas unitarias. resolves #49

test: Se ajustan pruebas unitarias

---

helpers/calculos.go
helpers/documentos.go

feat: Se corrige calculo de titan para posgrados y se ajusta horas a mostrar en los cuadros de vinculación. 
resolves udistrital/resoluciones_cliente_v2#63

feat: Se corrige calculo para posgrados

---

helpers/resoluciones.go

feat: Se amplía consulta docente para que tenga en cuenta vinculaciones modificadas. 
resolves udistrital/resoluciones_cliente_v2#72

feat: Se amplía consulta docente

---

helpers/documentos.go

feat: Texto justificado en los pdfs de las resoluciones. resolves udistrital/resoluciones_cliente_v2#73

feat: Texto justificado en resoluciones.

---

controllers/expedir_resolucion.go
controllers/gestion_plantillas.go
controllers/gestion_resoluciones.go
controllers/gestion_vinculaciones.go
helpers/vinculaciones.go
routers/commentsRouter_controllers.go
swagger/swagger.json

feat: Se genera controlador y se aísla lógica para calculo del numero de semanas. resolves udistrital/resoluciones_cliente_v2#74

feat: Controlador y lógica para calculo de semanas

---

.drone.yml
go.mod
go.sum
helpers/documentos.go
main.go

feat: Se ajusta presentación de cancelaciones según nivel  Cambio de librería para auditoria. resolves udistrital/resoluciones_cliente_v2#80

feat: Se ajusta presentación de cancelaciones

---

helpers/expedir_resoluciones.go
helpers/vinculaciones.go
models/contrato_cancelar.go
models/expedicion_cancelacion.go
models/expedicion_resolucion.go
swagger/swagger.json

Ajustes cancelaciones. resolves #59

Ajustes cancelaciones

---

.drone.yml
README.md
controllers/gestion_vinculaciones.go
go.mod
helpers/expedir_resolucion.go
helpers/resoluciones.go
helpers/vinculaciones.go
models/rp_seleccionado.go
routers/commentsRouter_controllers.go
swagger/swagger.json

feat: Se desarrolla funcionalidad de registros presupuestales y se mejora filtro de resoluciones. resolves udistrital/resoluciones_cliente_v2#85

feat: Se desarrolla funcionalidad de registros presupuestales

---

helpers/documentos.go
helpers/resoluciones.go

feat: Se corrigen hallazgos de pruebas funcionales

feat: Se corrigen hallazgos de pruebas funcionales

---

helpers/documentos.go
helpers/resoluciones.go

management: Corrección de hallazgos udistrital/resoluciones_cliente_v2#93

management: Corrección de hallazgos

---

helpers/expedir_resoluciones.go

fix: se corrige error en expedición de cancelaciones. udistrital/resoluciones_cliente_v2#93

fix: se corrige error en expedición de cancelaciones.

---

helpers/expedir_resoluciones.go
helpers/resoluciones.go

management: release

---

helpers/expedir_resolucion.go
helpers/expedir_resoluciones.go
helpers/resoluciones.go

fix: Ajustes Prod https://github.com/udistrital/resoluciones_cliente_v2/issues/100

fix: Ajustes Prod

---

helpers/docentes.go
helpers/documentos.go
helpers/expedir_resolucion.go
helpers/plantillas.go
helpers/vinculaciones.go

fix: Correccion de hallazgos encontrados en preparación de pruebas piloto

fix: Correccion de hallazgos encontrados en preparación de pruebas piloto

---

helpers/docentes.go
helpers/documentos.go
helpers/expedir_resolucion.go
helpers/plantillas.go
helpers/resoluciones.go
helpers/vinculaciones.go

management: Actualización prod. https://github.com/udistrital/resoluciones_cliente_v2/issues/109

management: Actualización prod

---

helpers/expedir_resolucion.go
helpers/expedir_resoluciones.go
helpers/nomina.go
helpers/vinculaciones.go
models/contrato_cancelacion.go

udistrital/resoluciones_cliente_v2#129

Ajuste para cancelaciones

---

helpers/expedir_resoluciones.go
helpers/vinculaciones.go
models/contrato_reduccion.go
models/objeto_modificaciones.go
models/vinculacion_docente.go
swagger/swagger.json
swagger/swagger.yml

udistrital/resoluciones_cliente_v2#137

feat: Reducciones para posgrado 

---

helpers/documentos.go
helpers/expedir_resoluciones.go
helpers/vinculaciones.go
models/contrato_reduccion.go
models/objeto_modificaciones.go
models/vinculacion_docente.go
swagger/swagger.json
swagger/swagger.yml

https://github.com/udistrital/resoluciones_cliente_v2/issues/137

reducciones posgrado

---

helpers/nomina.go
models/contrato_cancelacion.go

https://github.com/udistrital/resoluciones_cliente_v2/issues/137

feat: Cancelacion posgrado 

---

controllers/reporte_financiera.go
helpers/reporte_financiera.go
models/datos_reporte.go
models/reporte_financiera.go
routers/commentsRouter_controllers.go
routers/router.go
swagger/swagger.json
swagger/swagger.yml

udistrital/resoluciones_cliente_v2#143

feat: Reporte a financiera

---

helpers/documentos.go

udistrital/resoluciones_cliente_v2#160

fix: Ajuste valor total contrato 

---

controllers/gestion_vinculaciones.go
helpers/vinculaciones.go
models/edicion_vinculaciones.go
routers/commentsRouter_controllers.go
swagger/swagger.json
swagger/swagger.yml

udistrital/resoluciones_cliente_v2#160

fix: Modificacion de vinculaciones al cambiar cant semanas en vinculacion

---

helpers/documentos.go

udistrital/resoluciones_cliente_v2#160

fix: Ajuste valores resoluciones adicion y reduccion 

---

helpers/expedir_resolucion.go
helpers/expedir_resoluciones.go
helpers/nomina.go

udistrital/resoluciones_cliente_v2#160

fix: Cambios para cancelación 

---

helpers/vinculaciones.go

Se hace ajuste de prima de servicios cuando se hace una reduccion de semanas en resolucion de cancelacion

fix: Prima servicios dedicacion TCO

---

helpers/nomina.go
helpers/vinculaciones.go
models/datos_vinculacion.go

#194 se usa el tipo resolucion para calcular desagregado de una cancelacion

hotfix prima servicios cancelaciones

---

Dockerfile

fix: Se actualiza versión de python en Dockerfile

---

helpers/calculos.go

https://github.com/udistrital/resoluciones_cliente_v2/issues/229 paso a release para realizar pruebas en sisgplan (se agrega aplicacion_id en query)

hotfix: servicio desagregado dve planeacion
